### ISSUE TITLE
Change absolute to relative links

### ISSUE THREAD

**Issue by msmorul** [SESYNC-ci/teaching-lab#3]
Lots of images/css references use /css/.... rather than css/... this ends up breaking the front page if you change it to a different url, ie / -> /xjc for the multi-class setup. Links to the actual services will need to be updated as well.

**Comment by itcarroll** [comment]
New dev build (many other changes on top of this one) should complete in ~20 min. 

`docker pull sesync/teaching-lab:dev`

**Comment by itcarroll** [comment]
confirmed rel paths working
