### ISSUE TITLE
Jupyterhub urls

### ISSUE THREAD

**Issue by msmorul** [SESYNC-ci/teaching-lab#4]
It appears to use absolute paths when it loads various page assets causing the docker/lab setup to fail

> 
> 
> <link rel="stylesheet" href="/jupyterhub/hub/static/css/style.min.css?v=d96e0760e0c2b7356ce89635b646c350" type="text/css"/>
> --
>   |  
>   | <script src="/jupyterhub/hub/static/components/requirejs/require.js?v=6da8be361b9ee26c5e721e76c6d4afce" type="text/javascript" charset="utf-8"></script>

**Comment by itcarroll** [comment]
i may have set something up wrong in jupyterhub, which does it's own layer of proxying. if there is a way of passing the XXX string into the docker container as an env variable at run time, though, I think it could be appended to [this configurable path](../blob/master/root/etc/jupyterhub/jupyterhub_config.py#L60).

**Comment by msmorul** [comment]
Yeah, if you can set it based on an environment variable we can pass that
during container startup as follows:

IFS=$'\n';
for i in $(cat /etc/nginx/conf.d/maps.conf | grep 127); do
  prefix=$(echo $i | cut -c 6-8);
  port=$(echo $i | cut -c 23-26);
  prefixmap[$port]=$prefix ;
done
for i in {0..10} ; do
  port=$(printf '3%03i' $i);
  docker run -d -e USER=sesync -e PREFIX=${prefixmap[$port]} -p ${port}:80
sesync/teaching-lab:dev ;
done

**Comment by msmorul** [comment]
hmm, forwards are acting wonky on it:
```
> GET /jupyterhub/login HTTP/1.1
> Host: docker01.research.sesync.org:3011
> User-Agent: curl/7.47.0
> Accept: */*
> 
< HTTP/1.1 302 Found
< Server: nginx/1.10.3
< Date: Thu, 03 Aug 2017 13:07:48 GMT
< Content-Type: text/html; charset=UTF-8
< Content-Length: 0
< Connection: keep-alive
< location: /jupyterhub/hub/jupyterhub/login
< content-security-policy: frame-ancestors 'self'; report-uri /jupyterhub/hub/security/csp-report
```

**Comment by itcarroll** [comment]
Resolved by letting the teaching-lab container's nginx handle port 80 (not the host's nginx).
